routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
Auth::loginUsingId(1);
Route::resource('blog', PostsController::class);

app/Models/Media.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Media extends Model
{
    use HasFactory;
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'html'];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Http\Resources\PostResources;
use App\Models\Post;

class PostsController extends Controller
{
    public function index()
    {
        $posts = PostResources::collection(Post::all());
        return view('posts.index', compact('posts'));
    }

    public function create()
    {
        return view('posts.create');
    }

    public function show($id)
    {
        $post = new PostResources(Post::findOrFail($id));
        return view('posts.show', compact('post'));
    }

    public function edit($id)
    {
        $post = new PostResources(Post::findOrFail($id));
        return view('posts.edit', compact('post'));
    }

    public function store(PostRequest $request)
    {
        $validatedData = $request->validated();

        $post = Post::create($validatedData);

        return redirect()->route('blog.index');

    }

    public function update(PostRequest $request, $id)
    {
        $validatedData = $request->validated();

        $post = Post::findOrFail($id);
        $post->update($validatedData);

        return redirect()->route('blog.index');
    }


    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        $post->delete();

        return redirect()->route('blog.index');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=yes, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Laravel blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>
<div class="container-fluid">
    <div class="container">
        <div>
            <a href="{{ route('blog.index') }}">Blog</a>
            <a href="{{ route('blog.create') }}">Create</a>
        </div>
        @yield('content')
    </div>
</div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Create</h1>

    <form method="POST" action="{{ route('blog.store') }}">
        @csrf

        @include('posts.form')

        <button type="submit">Create</button>
    </form>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1>Edit</h1>

    <form method="POST" action="{{ route('blog.update', $post->id) }}">
        @csrf
        @method('PUT')

        @include('posts.form')

        <button type="submit">Save</button>
    </form>

@endsection

resources/views/posts/form.blade.php
<div class="mb-3">
    <input class="w-100" placeholder="Title" type="text" name="title" id="title" value="{{ $post->title ?? '' }}">
</div>
<div>
    <textarea name="html" id="html" rows="30">{{ $post->html ?? '' }}</textarea>
</div>
<script>
    tinymce.init({
        selector: '#html'
    });
</script>

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="text-center">Posts</h1>

    @foreach ($posts as $post)
        <div>
            <a href="{{ route('blog.show', $post->id) }}"><h3>{{ $post->title }}</h3></a>
            {{$post->created_at}}
            <p>{!! $post->html !!}</p>
        </div>
        <hr>

    @endforeach
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <a class="text-center" href="{{ route('blog.edit', $post->id) }}"><h1>{{ $post->title }}</h1></a>
    <p>{!! $post->html !!}</p>
@endsection